language: python
python:
  - "3.5"
addons:
  apt_packages:
    - enchant
    - aspell
    - aspell-en
    - ispell
    - iamerican
env:
  - BOTO_CONFIG=/dev/null
install:
  - pip install -U pip wheel setuptools
  - "pip install --no-binary :all: -r testrequirements.txt"
  - pip install -r requirements.txt
  - pip install -e .

script: "trial buildbot_UnrealEngine.test"
